services:
  redis:
    image: redis:latest
    container_name: "redis-for-moderation"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - redis_network

  bot:
    container_name: "bot-moderator"
    build:
      dockerfile: ./bot/Dockerfile
    env_file: ./bot/.env
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    networks:
      - redis_network
    command: >
      sh -c "uv run python -m bot.main"

  server:
    container_name: "server-moderator"
    build:
      dockerfile: ./server/Dockerfile
    env_file: ./server/.env
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    networks:
      - redis_network
    command: >
      sh -c "uv run python -m server.main"

networks:
  redis_network:
    driver: bridge