"""The module responsible for the schemes for moderation."""

from pydantic import BaseModel, Field


class ModerationIn(BaseModel):
    """The schema of the message that will need to be moderated."""

    msg_id: str = Field(..., description="Message ID")
    msg: str = Field(..., description="Message text")


class ModerationOut(BaseModel):
    """The schema of the moderation result."""

    msg_id: str = Field(..., description="Message ID")
    generated_by_llm: bool = Field(
        ..., description="Is the message generated by a neural network?"
    )
    toxic: bool = Field(..., description="Is the message toxic?")
